// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cozvrqwldxhrrglpalbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvenZycXdsZHhocnJnbHBhbGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNjM2NjksImV4cCI6MjA1NTYzOTY2OX0.MPEi1_jBD_nC5zj2O1EF0CP22bYP7E0Lf7nHvwFnEcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);